[package]
name = "wmo"
description = "Reads WoW 1.12.1 WMO buildings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
wowfile = { path = "../wowfile" }

[lints]
workspace = true

[dev-dependencies]
mpq = { path = "../mpq" }
