[package]
name = "terrain"
description = "Terrain and water meshes, and height queries"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
adt = { path = "../adt" }
mpq = { path = "../mpq" }
wdt = { path = "../wdt" }

[lints]
workspace = true
