[package]
name = "model"
description = "Models ready to draw: M2 and WMO batches, bounds, collision and animation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
blp = { path = "../blp" }
m2 = { path = "../m2" }
mpq = { path = "../mpq" }
wmo = { path = "../wmo" }
wowfile = { path = "../wowfile" }

[lints]
workspace = true
