[package]
name = "world"
description = "Draws the world in Bevy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
avian3d.workspace = true
bevy.workspace = true
blp = { path = "../blp" }
bytemuck = { version = "1", features = ["derive"] }
character = { path = "../character" }
dbc = { path = "../dbc" }
image = { version = "0.25", default-features = false }
light = { path = "../light" }
model = { path = "../model" }
mpq = { path = "../mpq" }
terrain = { path = "../terrain" }
wdl = { path = "../wdl" }
wdt = { path = "../wdt" }

[lints]
workspace = true
